// admin-web/src/views/authority-mgt/authority-mgt.tsx
import ElementUI from 'element-plus'

import { Watch } from 'vue-facing-decorator'
import { Component, Confirm } from '@/components/decorator'
import { Base } from '@/views/base'
import {
  Button,
  Buttons,
  Dialog,
  Form,
  FormItem,
  Input,
  Switch,
  TableEx,
  TableExColumnProp,
} from '@/components'
import { OperateModel } from '@/utils'
import { QueryOpEnum } from '@/models/enum'

export type AuthorityDataType = {
  id?: string
  name?: string
  text?: string
  status?: boolean
}
@Component
export class AuthorityMgt extends Base {
  $refs: { table: TableEx; form: ElementUI.Form }
  op: OperateModel<{ op: string; data?: any }> = null
  loadedData: any = null
  created() {
    this.init()
  }
  mounted() {
    this.runLoadData()
  }

  columns: TableExColumnProp[] = []
  init() {
    this.op = this.getOpModel({
      fn: ({ op, data }) => {
        if (op === 'save') return this.save(data)
        else if (op === 'del') return this.del(data)
      },
    })
    this.loadedData = {
      rows: [],
      total: null,
    }
    this.columns = [
      {
        prop: 'name',
        label: '名字',
      },
      {
        prop: 'text',
        label: '显示',
      },
      {
        prop: 'status',
        label: '状态',
        render: (h, params) => {
          return params.row.status ? '启用' : '禁用'
        },
      },
      {
        prop: 'op',
        label: '操作',
        fixed: 'right',
        width: '140',
        render: (h, params) => {
          let data = params.row
          return (
            <div>
              <Buttons
                defaultType="text"
                items={[
                  {
                    label: '修改',
                    click: () => {
                      this.editClick(data)
                    },
                  },
                  {
                    label: data.status ? '禁用' : '启用',
                    click: () => {
                      this.enableToggleClick(data)
                    },
                  },
                  {
                    label: '删除',
                    click: () => {
                      this.delClick(data)
                    },
                  },
                ]}
              ></Buttons>
            </div>
          )
        },
      },
    ]
  }

  @Watch('$route')
  private watchRoute() {
    this.runLoadData()
  }

  private toQuery(opt) {
    let model = this.$refs.table.model
    this.gotoPage(
      this.$utils.getUrl({
        path: this.$route.path,
        query: {
          ...this.$route.query,
          ...this.$utils.tableExModel2Query({
            model,
            refresh: opt.refresh,
          }),
        },
      }),
    )
  }

  private runLoadData() {
    let table = this.$refs.table
    if (table) {
      this.$utils.query2TableExModel({
        query: this.$route.query,
        model: table.model,
      })
      table.loadData()
    }
  }

  async loadData(opt) {
    let model = this.$refs.table.model
    let data = this.$utils.tableExModel2ApiParams({ model })
    let rs = await this.$api.sysAuthorityQuery({
      ...data,
    })
    this.loadedData = rs
    return rs
  }

  private getNewData() {
    return {
      id: null,
      name: '',
      text: '',
      status: true,
    } as AuthorityDataType
  }
  editingData: AuthorityDataType = null
  addClick() {
    this.editingData = this.getNewData()
    this.editData()
  }

  editClick(row) {
    this.editingData = { ...row }
    this.editData()
  }
  private originalData: AuthorityDataType = null
  private editData() {
    this.originalData = this.$utils.clone(this.editingData)
    if (this.editingData.id) {
      this.formOpt.name.disabled = true
      this.formOpt.name.showDisabled = true
    } else {
      this.formOpt.name.disabled = false
      this.formOpt.name.showDisabled = false
    }
    this.$refs.form?.resetFields()
    this.editDiaVisible = true
  }

  async saveClick() {
    let rs = await this.op.run({ op: 'save', data: this.editingData })
    if (rs.success) this.runLoadData()
  }
  async save(data: AuthorityDataType) {
    if (this.editDiaVisible) await this.$utils.validateForm(this.$refs.form)
    if (!data.id) await this.$api.sysAuthorityCreate(data)
    else await this.$api.sysAuthorityUpdate(data)
    this.editDiaVisible = false
  }

  async enableToggleClick(data) {
    let rs = await this.op.run({
      op: 'save',
      data: { id: data.id, status: !data.status },
    })
    if (rs.success) this.runLoadData()
  }

  @Confirm('确认删除?')
  async delClick(row) {
    let rs = await this.op.run({ op: 'del', data: row })
    if (rs.success) this.runLoadData()
  }

  async del(data: AuthorityDataType) {
    await this.$api.sysAuthorityDelete({ id: data.id })
  }

  rules = {
    name: [{ required: true }],
    text: [{ required: true }],
  }

  editDiaVisible = false
  private formOpt = {
    name: {
      showDisabled: false,
      disabled: false,
    },
  }
  renderForm() {
    return (
      <div v-loading={this.op.loading}>
        <Form
          ref="form"
          props={{ model: this.editingData }}
          rules={this.rules}
          labelPosition="top"
          inline
        >
          <FormItem prop="name">
            <span slot="label">
              名称
              {this.formOpt.name.showDisabled && (
                <Button
                  type="text"
                  on-click={() => {
                    this.formOpt.name.disabled = !this.formOpt.name.disabled
                    if (this.formOpt.name.disabled) {
                      this.editingData.name = this.originalData.name
                    }
                  }}
                >
                  {this.formOpt.name.disabled ? '修改' : '取消'}
                </Button>
              )}
            </span>
            <Input
              v-model={this.editingData.name}
              disabled={this.formOpt.name.disabled}
            />
          </FormItem>
          <FormItem label="显示" prop="text">
            <Input v-model={this.editingData.text} />
          </FormItem>
          <br />
          <FormItem label="启用状态" prop="status">
            <Switch v-model={this.editingData.status}></Switch>
          </FormItem>
        </Form>
        <div>
          <Button on-click={this.saveClick}>保存</Button>
        </div>
      </div>
    )
  }
  render() {
    let data = this.loadedData
    return (
      <div>
        <TableEx
          ref="table"
          columns={this.columns}
          tableProps={{ data: data.rows, stripe: true }}
          total={data.total}
          pagePosition="both"
          loadFn={this.loadData}
          queryProps={[
            {
              prop: 'name',
              label: '名字',
              matchType: QueryOpEnum.$like,
            },
            {
              prop: 'text',
              label: '显示',
              matchType: QueryOpEnum.$like,
            },
            {
              prop: 'status',
              label: '状态',
              propType: 'select',
              data: [
                {
                  label: '启用',
                  value: 1,
                },
                {
                  label: '禁用',
                  value: 0,
                },
              ],
            },
          ]}
          on-query-trigger={this.toQuery}
          buttons={[
            {
              name: 'query',
              label: '查询',
              type: 'primary',
              click: () => {
                this.toQuery({ refresh: true })
              },
            },
            {
              name: 'add',
              label: '添加',
              click: this.addClick,
            },
          ]}
        ></TableEx>
        <Dialog
          appendToBody
          visible={this.editDiaVisible}
          on={{ 'update:visible': (v) => (this.editDiaVisible = v) }}
          title={this.editingData?.id ? '修改' : '新增'}
        >
          {this.editingData && this.renderForm()}
        </Dialog>
      </div>
    )
  }
}

// admin-web/src/views/authority-mgt/authority-mgt.vue
<template>
  <div>
    <TableEx
      ref="table"
      :columns="columns"
      :tableProps="{ data: loadedData.rows, stripe: true }"
      :total="loadedData.total"
      pagePosition="both"
      :loadFn="loadData"
      :queryProps="queryProps"
      @query-trigger="toQuery"
      :buttons="tableButtons"
    />
    <el-dialog
      append-to-body
      v-model="editDiaVisible"
      :title="editingData?.id ? '修改' : '新增'"
    >
      <template v-if="editingData">
        <div v-loading="op.loading">
          <el-form
            ref="form"
            :model="editingData"
            :rules="rules"
            label-position="top"
            inline
          >
            <el-form-item prop="name">
              <template #label>
                名称
                <el-button
                  v-if="formOpt.name.showDisabled"
                  type="primary"
                  link
                  @click="toggleNameEdit"
                >
                  {{ formOpt.name.disabled ? '修改' : '取消' }}
                </el-button>
              </template>
              <el-input
                v-model="editingData.name"
                :disabled="formOpt.name.disabled"
              />
            </el-form-item>
            <el-form-item label="显示" prop="text">
              <el-input v-model="editingData.text" />
            </el-form-item>
            <el-form-item label="启用状态" prop="status">
              <el-switch v-model="editingData.status" />
            </el-form-item>
          </el-form>
          <div>
            <el-button @click="saveClick">保存</el-button>
          </div>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script lang="tsx" setup>
import { ref, reactive, onMounted, watch } from 'vue'
import { TableEx, Buttons, TableExInstance } from '@/components'
import { QueryOpEnum } from '@/models/enum'

import Base from '../base'
import { usePlugins } from '@/plugins'
import { useRoute } from 'vue-router'
import { FormInstance } from 'element-plus'
import { Confirm } from '@/components/decorator'

const { $api, $utils } = usePlugins()
const { getOpModel, gotoPage } = Base()
const $route = useRoute()

export type AuthorityDataType = {
  id?: string
  name?: string
  text?: string
  status?: boolean
}

const op = ref(
  getOpModel<{ op: string; data: any }>({
    fn: ({ op, data }) => {
      if (op === 'save') return save(data)
      if (op === 'del') return del(data)
    },
  }),
)

const loadedData = ref({
  rows: [],
  total: null,
})

const editingData = ref(null)
const editDiaVisible = ref(false)

const rules = {
  name: [{ required: true }],
  text: [{ required: true }],
}

const formOpt = ref({
  name: {
    showDisabled: false,
    disabled: false,
  },
})

const columns = [
  {
    prop: 'name',
    label: '名字',
  },
  {
    prop: 'text',
    label: '显示',
  },
  {
    prop: 'status',
    label: '状态',
    render: (params) => {
      return <span>{params.row.status ? '启用' : '禁用'}</span>
    },
  },
  {
    prop: 'op',
    label: '操作',
    fixed: 'right',
    width: '140',
    render: (params) => {
      const data = params.row
      return (
        <div>
          <Buttons
            defaultType="text"
            items={[
              { label: '修改', click: () => editClick(data) },
              {
                label: data.status ? '禁用' : '启用',
                click: () => enableToggleClick(data),
              },
              { label: '删除', click: () => delClick(data) },
            ]}
          />
        </div>
      )
    },
  },
]

const queryProps = [
  {
    prop: 'name',
    label: '名字',
    matchType: QueryOpEnum.$like,
  },
  {
    prop: 'text',
    label: '显示',
    matchType: QueryOpEnum.$like,
  },
  {
    prop: 'status',
    label: '状态',
    propType: 'select',
    data: [
      { label: '启用', value: 1 },
      { label: '禁用', value: 0 },
    ],
  },
]

const tableButtons = [
  {
    name: 'query',
    label: '查询',
    type: 'primary',
    click: () => toQuery({ refresh: true }),
  },
  {
    name: 'add',
    label: '添加',
    click: () => addClick(),
  },
]

const loadData = async (opt) => {
  const model = table.value.model
  const data = $utils.tableExModel2ApiParams({ model })
  const rs = await $api.sysAuthorityQuery({ ...data })
  loadedData.value = rs
  return rs
}

class FunctionWrapper {
  @Confirm((data) => `确认删除[${data.text}(${data.name})]?`)
  static async delClick(data: AuthorityDataType) {
    const rs = await op.value.run({ op: 'del', data })
    if (rs.success) runLoadData()
  }
}

const addClick = () => {
  editingData.value = getNewData()
  editData()
}

const editClick = (row) => {
  editingData.value = { ...row }
  editData()
}

const editData = () => {
  if (editingData.value.id) {
    formOpt.value.name = {
      ...formOpt.value.name,
      disabled: true,
      showDisabled: true,
    }
  } else {
    formOpt.value.name = {
      ...formOpt.value.name,
      disabled: false,
      showDisabled: false,
    }
  }
  editDiaVisible.value = true
}

const saveClick = async () => {
  const rs = await op.value.run({ op: 'save', data: editingData.value })
  if (rs.success) runLoadData()
}

const save = async (data) => {
  if (editDiaVisible.value) await $utils.validateForm(form.value)
  if (!data.id) await $api.sysAuthorityCreate(data)
  else await $api.sysAuthorityUpdate(data)
  editDiaVisible.value = false
}

const enableToggleClick = async (data) => {
  const rs = await op.value.run({
    op: 'save',
    data: { id: data.id, status: !data.status },
  })
  if (rs.success) runLoadData()
}

const delClick = FunctionWrapper.delClick

const del = async (data) => {
  await $api.sysAuthorityDelete({ id: data.id })
}

const toQuery = (opt) => {
  const model = table.value.model
  const query = $utils.tableExModel2Query({ model, refresh: opt.refresh })
  const path = $utils.getUrl({ path: $route.path, query })
  gotoPage(path)
}

const runLoadData = () => {
  if (table.value) {
    $utils.query2TableExModel({ query: $route.query, model: table.value.model })
    table.value.loadData()
  }
}

const getNewData = () => ({
  id: null,
  name: '',
  text: '',
  status: true,
})

const toggleNameEdit = () => {
  formOpt.value.name.disabled = !formOpt.value.name.disabled
  if (formOpt.value.name.disabled) {
    editingData.value.name = originalData.value.name
  }
}

const table = ref<TableExInstance>(null)
const form = ref<FormInstance>(null)
const originalData = ref(null)

watch(() => $route.fullPath, runLoadData)

onMounted(runLoadData)
</script>
