// admin-web/src/views/error/error.tsx
import { Component, Prop, Vue } from '@/components/decorator'
import { Card, Result } from '@/components'
import { Base } from '../base'

class ErrorProp {
  @Prop()
  title?: string
}
@Component({
  extends: Base,
  props: ErrorProp,
})
export class ErrorView extends Vue<ErrorProp, Base> {
  render() {
    return (
      <Card>
        <Result title={this.title || 'Not Found'} icon="error"></Result>
      </Card>
    )
  }
}

// admin-web/src/views/error/error.vue
<template>
  <el-card>
    <el-result :title="title || 'Not Found'" icon="error" />
  </el-card>
</template>

<script lang="ts" setup>
import { defineComponent, PropType } from 'vue'

defineComponent({
  name: 'ErrorView',
})

defineProps({
  title: {
    type: String as PropType<string>,
    required: false,
  },
})
</script>
