// admin-web/src/views/comps/role-tags/role-tags.tsx
import { Watch } from 'vue-facing-decorator'

import { Component, Vue, Prop } from '@/components/decorator'
import { Base } from '@/views/base'
import { RoleDataType } from '@/views/role-mgt'
import { Popover, Tags } from '@/components'

class RoleTagsProp {
  @Prop()
  items: RoleDataType[]
}

@Component({
  props: RoleTagsProp,
  extends: Base,
})
export class RoleTags extends Vue<RoleTagsProp, Base> {
  render() {
    return (
      <div>
        {this.items.map((ele) => {
          return (
            <Popover trigger="hover" disabled={!ele.authorityList.length}>
              <Tags items={[ele]} slot="reference"></Tags>
              <Tags items={ele.authorityList}></Tags>
            </Popover>
          )
        })}
      </div>
    )
  }
}

// admin-web/src/views/comps/role-tags/role-tags.vue
<template>
  <div>
    <el-popover
      v-for="(ele, index) in items"
      :key="index"
      trigger="hover"
      :disabled="!ele.authorityList.length"
    >
      <template #reference>
        <Tags :items="[ele]" />
      </template>
      <Tags :items="ele.authorityList" />
    </el-popover>
  </div>
</template>

<script lang="ts" setup>
import { PropType } from 'vue'
import { Tags } from '@/components'
import { RoleDataType } from '@/views/role-mgt'

defineProps({
  items: {
    type: Array as PropType<RoleDataType[]>,
    required: true,
  },
})
</script>
