// admin-web/src/AppX.vue
<template>
  <Buttons
    :items="[
      {
        name: 'query',
        label: '查询',
        type: 'primary',
        click: () => {
          dialog.toggle()
        },
      },
    ]"
  ></Buttons>
  <ConfirmDialog ref="dialog"> 测试 </ConfirmDialog>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { Buttons, ConfirmDialog } from './components'
const dialog = ref<InstanceType<typeof ConfirmDialog>>(null)
</script>

// admin-web/src/AppX.tsx
import { Component } from 'vue-facing-decorator'

import { Base } from '@/views/base'
import { Buttons } from '@/components'
@Component
export default class App extends Base {
  render() {
    return (
      <Buttons
        items={[
          {
            name: 'query',
            label: '查询',
            type: 'primary',
            click: () => {
              console.log(111111)
            },
          },
        ]}
      ></Buttons>
    )
  }
}
