// admin-web/src/components/confirm-dialog/confirm-dialog.tsx
import { Prop, Component, Vue } from '@/components/decorator'

import { Button, Row, Col, Dialog } from '../ui'
import { BaseComp } from '../base-comp'
import styles from './index.module.less'

type BtnType = {
  text: string
  type?: string
  loading?: boolean
  onClick?: (ele: BtnType, idx: number) => any
}

export class ConfirmDialogProp {
  @Prop()
  title?: string

  @Prop({ default: false })
  loading?: boolean

  @Prop()
  btnList?: BtnType[]

  @Prop()
  ok?: (ele: BtnType) => any | Promise<any>

  @Prop()
  cancel?: (ele: BtnType) => void
}

@Component({
  extends: BaseComp,
  props: ConfirmDialogProp,
})
export class ConfirmDialog extends Vue<ConfirmDialogProp, BaseComp> {
  show = false
  toggle(show?: boolean) {
    this.show = typeof show === 'boolean' ? show : !this.show
  }

  private get innerBtnList() {
    return (
      this.btnList || [
        {
          text: '取消',
          onClick: (e) => {
            this.cancel && this.cancel(e)
            this.toggle()
          },
        },
        {
          text: '确认',
          type: 'primary',
          onClick: async (e, idx) => {
            if (this.ok) {
              if (this.loading) {
                e.loading = true
                this.$forceUpdate()
              }
              await this.ok(e)
              if (this.loading) {
                e.loading = false
                this.$forceUpdate()
              }
            }
            this.toggle()
          },
        },
      ]
    )
  }

  renderBtn() {
    const btnList = this.innerBtnList

    return (
      <Row gutter={5} type="flex" justify="end">
        {btnList.map((ele, idx) => {
          if (!ele.loading) {
            ele.loading = false
          }
          return (
            <Button
              type={ele.type as any}
              on-click={() => {
                ele.onClick && ele.onClick(ele, idx)
              }}
              loading={ele.loading}
            >
              {ele.text}
            </Button>
          )
        })}
      </Row>
    )
  }

  render() {
    return (
      <Dialog
        visible={this.show}
        title={this.title}
        appendToBody
        on={{
          'update:visible': (newVal) => (this.show = newVal),
        }}
      >
        {this.$slots.default}
        {this.renderBtn()}
      </Dialog>
    )
  }
}

// admin-web/src/components/confirm-dialog/confirm-dialog.vue
<template>
  <el-dialog v-model="show" :title="title" append-to-body>
    <slot></slot>
    <el-row :gutter="5" type="flex" justify="end">
      <el-button
        v-for="(btn, idx) in innerBtnList"
        :key="idx"
        :type="btn.type as any"
        :loading="btn.loading"
        @click="btn.onClick && btn.onClick(btn, idx)"
      >
        {{ btn.text }}
      </el-button>
    </el-row>
  </el-dialog>
</template>

<script lang="ts" setup>
import { defineComponent, ref, computed, PropType } from 'vue'

defineComponent({
  name: 'ConfirmDialog',
})

type BtnType = {
  text: string
  type?: string
  loading?: boolean
  onClick?: (ele: BtnType, idx: number) => any
}

const props = defineProps({
  title: {
    type: String,
    required: false,
  },
  loading: {
    type: Boolean,
    default: false,
  },
  btnList: {
    type: Array as PropType<BtnType[]>,
    required: false,
  },
  ok: {
    type: Function as PropType<(ele: BtnType) => any | Promise<any>>,
    required: false,
  },
  cancel: {
    type: Function as PropType<(ele: BtnType) => void>,
    required: false,
  },
})
const show = ref(false)

const toggle = (value?: boolean) => {
  show.value = typeof value === 'boolean' ? value : !show.value
}

const innerBtnList = computed(() => {
  return (
    props.btnList || [
      {
        text: '取消',
        onClick: (e: BtnType) => {
          props.cancel && props.cancel(e)
          toggle(false)
        },
      },
      {
        text: '确认',
        type: 'primary',
        onClick: async (e: BtnType) => {
          if (props.ok) {
            if (props.loading) {
              e.loading = true
            }
            await props.ok(e)
            if (props.loading) {
              e.loading = false
            }
          }
          toggle(false)
        },
      },
    ]
  )
})

defineExpose({
  toggle,
})
</script>

<style lang="less" scoped>
.content-box {
  min-height: 80px;
  margin: 10px 0;
}
</style>
