// admin-web/src/components/buttons/buttons.vue
<template>
  <div>
    <el-button
      v-for="(ele, index) in items"
      :key="index"
      :type="defaultType || (ele.type as any)"
      v-bind="ele"
      @click="handleClick(ele)"
    >
      {{ ele.label }}
    </el-button>
  </div>
</template>

<script lang="ts" setup>
import { defineComponent } from 'vue'

defineComponent({
  name: 'ButtonsComp',
})

export type ButtonItem = {
  name?: string
  label?: string
  type?: string
  click?: (opt?: { item: ButtonItem }) => any
}

defineProps<{
  defaultType?: String
  items: ButtonItem[]
}>()

function handleClick(ele: ButtonItem) {
  if (ele.click) {
    ele.click({ item: ele })
  }
}
</script>

// admin-web/src/components/buttons/buttons.tsx

import { Component, Vue, Prop, toNative } from '@/components/decorator'

import { Button } from '../ui'

export type ButtonItem = {
  name?: string
  label?: string
  type?: string
  click?: (opt?: { item: ButtonItem }) => any
}

@Component
export class Buttons extends Vue {
  @Prop()
  defaultType?: string

  @Prop()
  items: ButtonItem[]

  render() {
    return (
      <div>
        {this.items.map((ele) => {
          return (
            <Button
              props={
                {
                  type: this.defaultType,
                  ...ele,
                } as any
              }
              on-click={() => {
                ele.click && ele.click({ item: ele })
              }}
            >
              {ele.label}
            </Button>
          )
        })}
      </div>
    )
  }
}

export default toNative(Buttons)
